"""Quality-of-revenue workbook (Excel) with live formulas.

Historical data is written as blue hardcodes; every derived number is a formula, so the checks
(bridge roll-forward, AR roll-forward, invoice = revenue) recalculate if a data cell is edited.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from openpyxl import Workbook
from openpyxl.comments import Comment
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter as L

from saas_growth_quality.growth import load_marts, retention_12m
from saas_growth_quality.revenue_quality import build as build_rq

FONT = "Arial"
BLUE, BLACK, GREEN = "0000FF", "000000", "008000"
HEAD = PatternFill("solid", fgColor="DCE6F1")
KEY = PatternFill("solid", fgColor="FFFF00")
MM = '#,##0.0;(#,##0.0);"-"'
USD = '$#,##0;($#,##0);"-"'
PCT = '0.0%;(0.0%);"-"'
X = '0.00"x"'
NUM = '#,##0;(#,##0);"-"'


def _f(color=BLACK, bold=False, italic=False, size=10):
    return Font(name=FONT, color=color, bold=bold, italic=italic, size=size)


class Sheet:
    def __init__(self, wb: Workbook, name: str, title: str, subtitle: str = ""):
        self.ws = wb.create_sheet(name)
        self.ws["A1"], self.ws["A2"] = title, subtitle
        self.ws["A1"].font, self.ws["A2"].font = _f(bold=True, size=13), _f(italic=True, color="52514E")
        self.ws.column_dimensions["A"].width = 44
        self.ws.sheet_view.showGridLines = False

    def put(self, ref, value, fmt=None, color=None, fill=None, note=None):
        c = self.ws[ref]
        c.value = value
        if color is None:
            color = BLACK if isinstance(value, str) and value.startswith("=") else BLUE if isinstance(value, (int, float, np.number)) else BLACK
            if isinstance(value, str) and value.startswith("=") and "!" in value and value.count("!") == 1 and value[1:].split("!")[0].strip("'").isidentifier() and len(value) < 40:
                color = GREEN
        c.font = _f(color)
        if fmt:
            c.number_format = fmt
        if fill:
            c.fill = fill
        if note:
            c.comment = Comment(note, "Qiuli Lai")
        return c

    def header(self, row, labels, start_col=1):
        for i, lab in enumerate(labels):
            c = self.ws.cell(row=row, column=start_col + i, value=lab)
            c.font, c.fill = _f(), HEAD
            c.alignment = Alignment(horizontal="center" if i else "left", wrap_text=True)

    def section(self, ref, text):
        self.ws[ref] = text
        self.ws[ref].font = _f(bold=True, size=11)


def build_workbook(root: Path, path: Path, r: dict | None = None) -> Path:
    rq = build_rq(root)
    if r is None:
        from saas_growth_quality.diligence import build as build_dl
        r = {"dil": build_dl(root)}
    dil = r["dil"]
    marts = load_marts(root / "outputs" / "marts")
    am, bridge = marts["account_month"], marts["mrr_bridge"]
    wb = Workbook()
    wb.remove(wb.active)

    # ---------------- Cover
    cv = Sheet(wb, "Cover", "Quality of Revenue Workbook: Synthetic B2B SaaS Book", "As of July 2026. Prepared by Qiuli Lai.")
    lines = [
        ("Purpose", "Quality-of-revenue workbook for a B2B SaaS book acquired in Dec 2024: diligence benchmarking at close, underwriting forecast vs actual, and current ARR bridge, retention, concentration, revenue-to-cash, renewals and sensitivity."),
        ("Evidence boundary", "Customer-level data is synthetic. Its Dec 2023 to Dec 2024 retention was calibrated to SaaS Capital 2025 medians, so agreement in that window is by design. Jan 2025 onward is out of sample."),
        ("Units", "ARR and revenue in $ millions unless a header states $. ARR = 12 x month-end MRR. Percentages stored as fractions."),
        ("Colour legend", "Blue = hardcoded data or input; black = formula; green = link to another sheet; yellow fill = key assumption to review."),
        ("Checks", "ARR_Bridge row 12 and Revenue_to_Cash rows 7 and 15 must read zero. Plan_vs_Actual flags whether each month fell inside the band set at close."),
        ("Source code", "Generated by src/saas_growth_quality/qor_workbook.py from the SQL marts and cleaned tables."),
    ]
    for i, (k, v) in enumerate(lines):
        cv.put(f"A{4 + i}", k); cv.put(f"B{4 + i}", v)
        cv.ws[f"B{4 + i}"].alignment = Alignment(wrap_text=True, vertical="top")
        cv.ws.row_dimensions[4 + i].height = 30
    cv.ws.column_dimensions["A"].width = 20; cv.ws.column_dimensions["B"].width = 110
    cv.section("A11", "Sheets")
    for i, (n, d) in enumerate([("Summary", "Headline KPIs, all linked"), ("Inputs", "Assumptions and cited benchmarks"), ("Diligence", "Dec 2023 to Dec 2024 cohort vs SaaS Capital 2025 on matched cuts"), ("Plan_vs_Actual", "Underwriting forecast made at close vs actual, Jan 2025 to Jul 2026"),
                                ("ARR_Bridge", "Quarterly ARR roll-forward and growth quality ratios"),
                                ("Retention", "12-month cohort GRR/NRR now (Jul 2025 to Jul 2026); monthly-compounding trap"),
                                ("Concentration", "Top-N ARR share, HHI, trend"), ("Revenue_to_Cash", "Revenue, invoicing, collections, AR, DSO"),
                                ("Renewals", "ARR by renewal quarter and expected non-renewal"), ("Sensitivity", "Forward 12-month ARR by GRR and expansion"),
                                ("Customer_ARR", "Account-level ARR at July 2026"), ("Monthly_Bridge", "Monthly list-MRR bridge from SQL")]):
        cv.put(f"A{12 + i}", n); cv.put(f"B{12 + i}", d)

    # ---------------- Inputs
    inp = Sheet(wb, "Inputs", "Inputs and Benchmarks", "Blue cells are inputs; yellow cells are the assumptions most worth challenging.")
    inp.header(4, ["Assumption", "Value", "Basis"])
    inp.ws.column_dimensions["B"].width = 12; inp.ws.column_dimensions["C"].width = 95
    rows = [("Gross margin on subscription revenue", 0.75, PCT, "Assumption for illustration; replace with the company's subscription gross margin.", True),
            ("Days per quarter", 91.25, '0.00', "365 / 4, used for DSO.", False),
            ("Payment terms (months), informational", 1, '0', "Set in revenue_quality.py (PAYMENT_TERMS_MONTHS). The panel has no terms field; one-month terms are an assumption. Editing this cell does not re-time cash.", True)]
    for i, (a, v, fmt, basis, key) in enumerate(rows):
        r = 5 + i
        inp.put(f"A{r}", a); inp.put(f"B{r}", v, fmt, fill=KEY if key else None); inp.put(f"C{r}", basis)
    inp.section("A10", "External benchmarks (calibration inputs before close, checks after close)")
    inp.header(11, ["Benchmark", "Value", "Source, window and scope"])
    SC25 = "SaaS Capital 2025 retention benchmarks, >1,000 private B2B SaaS companies >$1M ARR, measured Dec 2023 to Dec 2024. https://www.saas-capital.com/wp-content/uploads/2025/09/RB32WS1-2025-B2B-SaaS-Retention-Benchmarks.pdf"
    bench = [("GRR median, all companies, SaaS Capital 2025", 0.91, SC25),
             ("NRR median, all companies, SaaS Capital 2025", 1.01, SC25),
             ("GRR median, Benchmarkit 2026", 0.84, "Benchmarkit 2026 SaaS and AI-native metrics; window, sample and definition not disclosed. https://www.benchmarkit.ai/2026-saas-ai-native-metrics"),
             ("NRR, usage-based pricing, Benchmarkit 2026", 1.08, "Same source."),
             ("NRR, seat-based pricing, Benchmarkit 2026", 0.98, "Same source."),
             ("Expansion share of net new ARR, median, Benchmarkit 2026", 0.40, "Same source. Compared here with expansion / (new logo + expansion) ARR; the source's denominator is not stated."),
             ("Revenue growth median, equity-backed, 2025", 0.25, "SaaS Capital 2026 growth benchmarks, all sizes (bootstrapped 20%). https://www.saas-capital.com/research/private-saas-company-growth-rate-benchmarks/"),
             ("GRR median, bootstrapped, SaaS Capital 2025", 0.92, SC25),
             ("NRR median, bootstrapped, SaaS Capital 2025", 1.04, SC25),
             ("GRR median, equity-backed, SaaS Capital 2025", 0.90, SC25),
             ("NRR median, equity-backed, SaaS Capital 2025", 1.01, SC25),
             ("GRR median, bootstrapped $3M-$20M, SaaS Capital 2026", 0.91, "SaaS Capital, published Apr 2026, calendar 2025 (inferred). https://www.saas-capital.com/blog-posts/benchmarking-metrics-for-bootstrapped-saas-companies/"),
             ("NRR median, bootstrapped $3M-$20M, SaaS Capital 2026", 1.03, "Same source.")]
    for i, (a, v, s_) in enumerate(bench):
        inp.put(f"A{12 + i}", a); inp.put(f"B{12 + i}", v, PCT); inp.put(f"C{12 + i}", s_)
    B = {"gm": "Inputs!$B$5", "dpq": "Inputs!$B$6", "sc_grr": "Inputs!$B$12", "sc_nrr": "Inputs!$B$13", "bm_grr": "Inputs!$B$14",
         "bm_usage": "Inputs!$B$15", "bm_seat": "Inputs!$B$16", "bm_exp": "Inputs!$B$17", "sc_growth": "Inputs!$B$18"}

    # ---------------- Monthly_Bridge (data)
    mb = Sheet(wb, "Monthly_Bridge", "Monthly List-MRR Bridge ($)", "From sql/03_mrr_bridge.sql. Opening excludes nothing; new = first billed month.")
    cols = ["month", "opening_list", "new_list", "expansion_list", "contraction_list", "churn_list", "closing_list"]
    mb.header(4, ["Month", "Opening", "New", "Expansion", "Contraction", "Churn", "Closing", "Roll-forward check", "Monthly GRR", "Monthly NRR"])
    for i, row in enumerate(bridge[cols].itertuples(index=False)):
        r = 5 + i
        mb.put(f"A{r}", row[0])
        for j, v in enumerate(row[1:]):
            mb.put(f"{L(2 + j)}{r}", round(float(v), 2), USD)
        mb.put(f"H{r}", f"=SUM(B{r}:F{r})-G{r}", USD)
        mb.put(f"I{r}", f"=IF(B{r}=0,0,1+(E{r}+F{r})/B{r})", '0.00%')
        mb.put(f"J{r}", f"=IF(B{r}=0,0,1+(D{r}+E{r}+F{r})/B{r})", '0.00%')
    mb_last = 4 + len(bridge)
    for c, w in zip("ABCDEFGHIJ", [12, 14, 12, 12, 12, 12, 14, 12, 11, 11]):
        mb.ws.column_dimensions[c].width = w

    # ---------------- ARR_Bridge (quarterly, $mm)
    q = rq["arr_bridge_q"] / 1e6
    ab = Sheet(wb, "ARR_Bridge", "Quarterly ARR Bridge ($mm, list price)", "Opening links to the prior quarter's closing; row 12 must be zero.")
    n = len(q)
    ab.header(4, ["$mm"] + list(q.index))
    labels = ["Opening ARR", "New logo ARR", "Expansion ARR", "Contraction ARR", "Churned ARR", "Closing ARR (roll-forward)",
              "Closing ARR per SQL mart", "Check: roll-forward minus mart"]
    for i, lab in enumerate(labels):
        ab.put(f"A{5 + i}", lab)
    for k, (qt, v) in enumerate(q.iterrows()):
        c = L(2 + k)
        ab.put(f"{c}5", round(v["opening"], 4) if k == 0 else f"={L(1 + k)}10", MM)
        for r, key in zip([6, 7, 8, 9], ["new", "expansion", "contraction", "churn"]):
            ab.put(f"{c}{r}", round(v[key], 4), MM)
        ab.put(f"{c}10", f"=SUM({c}5:{c}9)", MM)
        ab.put(f"{c}11", round(v["closing"], 4), MM)
        ab.put(f"{c}12", f"=ROUND({c}10-{c}11,3)", MM)
    ab.section("A14", "Growth quality ratios")
    ratios = [("Net new ARR", "={c}10-{c}5", MM), ("Gross new ARR (new + expansion)", "={c}6+{c}7", MM),
              ("Expansion share of gross new ARR", "=IF({c}16=0,0,{c}7/{c}16)", PCT),
              ("Quarterly gross retention (bridge)", "=IF({c}5=0,0,1+({c}8+{c}9)/{c}5)", PCT),
              ("Quarterly net retention (bridge)", "=IF({c}5=0,0,1+({c}7+{c}8+{c}9)/{c}5)", PCT),
              ("Quick ratio (gross new / gross losses)", "=IF(({c}8+{c}9)=0,0,{c}16/-({c}8+{c}9))", X),
              ("ARR growth, QoQ", "=IF({c}5=0,0,{c}10/{c}5-1)", PCT)]
    for i, (lab, f, fmt) in enumerate(ratios):
        r = 15 + i
        ab.put(f"A{r}", lab)
        for k in range(n):
            c = L(2 + k)
            ab.put(f"{c}{r}", f.format(c=c), fmt)
    ab.put("A22", "ARR growth, YoY")
    for k in range(4, n):
        c, c4 = L(2 + k), L(2 + k - 4)
        ab.put(f"{c}22", f"=IF({c4}10=0,0,{c}10/{c4}10-1)", PCT)
    last, first4 = L(1 + n), L(n - 2)
    ab.section("A24", "Trailing four quarters")
    ab.header(25, ["Metric", "TTM", "Benchmark", "Variance"])
    ttm = [("Opening ARR four quarters ago", f"={first4}5", MM, None),
           ("New logo ARR", f"=SUM({first4}6:{last}6)", MM, None),
           ("Expansion ARR", f"=SUM({first4}7:{last}7)", MM, None),
           ("Contraction + churn ARR", f"=SUM({first4}8:{last}9)", MM, None),
           ("Closing ARR", f"={last}10", MM, None),
           ("ARR growth, TTM", "=IF(B26=0,0,B30/B26-1)", PCT, B["sc_growth"]),
           ("Expansion share of gross new ARR, TTM", "=IF((B27+B28)=0,0,B28/(B27+B28))", PCT, B["bm_exp"]),
           ("Gross loss rate on opening ARR (bridge, includes in-year cohorts)", "=IF(B26=0,0,-B29/B26)", PCT, None)]
    for i, (lab, f, fmt, bm) in enumerate(ttm):
        r = 26 + i
        ab.put(f"A{r}", lab); ab.put(f"B{r}", f, fmt)
        if bm:
            ab.put(f"C{r}", f"={bm}", PCT); ab.put(f"D{r}", f"=B{r}-C{r}", PCT)
    ab.put("A35", "The bridge loss rate is not GRR: it includes losses from customers acquired during the year. Cohort GRR is on the Retention sheet.")
    ab.ws["A35"].font = _f(italic=True, color="52514E")
    for k in range(n + 1):
        ab.ws.column_dimensions[L(2 + k)].width = 11
    ab.ws.column_dimensions["A"].width = 58

    # ---------------- Retention
    rt = Sheet(wb, "Retention", "12-Month Cohort Retention (list MRR)", "Accounts active at Jul 2025, measured at Jul 2026. Groups under 30 accounts suppressed.")
    rt.header(4, ["Cohort", "Accounts", "Start ARR ($mm)", "12m GRR", "12m NRR", "Logo churn", "GRR vs SaaS Capital", "GRR vs Benchmarkit", "NRR vs SaaS Capital"])
    r = 5
    for g in [None, "segment", "pricing_model", "contract_term_months", "channel", "industry"]:
        t = retention_12m(am, "2026-07-01", g)
        for name, v in t.iterrows():
            label = "Portfolio" if g is None else f"{g.replace('_', ' ')}: {name}"
            rt.put(f"A{r}", label); rt.put(f"B{r}", int(v["accounts"]), NUM); rt.put(f"C{r}", round(v["start_mrr"] * 12 / 1e6, 4), MM)
            rt.put(f"D{r}", round(v["grr"], 5), PCT); rt.put(f"E{r}", round(v["nrr"], 5), PCT); rt.put(f"F{r}", round(v["logo_churn"], 5), PCT)
            rt.put(f"G{r}", f"=D{r}-{B['sc_grr']}", PCT); rt.put(f"H{r}", f"=D{r}-{B['bm_grr']}", PCT); rt.put(f"I{r}", f"=E{r}-{B['sc_nrr']}", PCT)
            if label == "contract term months: 1":
                ret_monthly_row = r
            if label == "pricing model: usage":
                usage_row = r
            if label == "pricing model: seat":
                seat_row = r
            r += 1
    rt.put(f"A{r + 1}", "Usage minus seat NRR (pp)"); rt.put(f"B{r + 1}", f"=E{usage_row}-E{seat_row}", PCT)
    rt.put(f"C{r + 1}", f"={B['bm_usage']}-{B['bm_seat']}", PCT); rt.put(f"D{r + 1}", "Benchmarkit 2026 gap in column C")
    trap = r + 3
    rt.section(f"A{trap}", "Definition trap: monthly retention compounded vs 12-month cohort")
    rt.header(trap + 1, ["Measure", "Value"])
    lo, hi = mb_last - 11, mb_last
    items = [("Average monthly GRR, last 12 months (Monthly_Bridge)", f"=AVERAGE(Monthly_Bridge!I{lo}:I{hi})", '0.00%'),
             ("Average monthly NRR, last 12 months", f"=AVERAGE(Monthly_Bridge!J{lo}:J{hi})", '0.00%'),
             ("Monthly GRR compounded to 12 months", f"=B{trap + 2}^12", PCT),
             ("Monthly NRR compounded to 12 months", f"=B{trap + 3}^12", PCT),
             ("12-month cohort GRR (row 5)", "=D5", PCT), ("12-month cohort NRR (row 5)", "=E5", PCT)]
    for i, (lab, f, fmt) in enumerate(items):
        rt.put(f"A{trap + 2 + i}", lab); rt.put(f"B{trap + 2 + i}", f, fmt)
    rt.put(f"A{trap + 9}", "Compounded monthly GRR sits well below cohort GRR. Two mechanisms are likely, not decomposed here: each monthly usage dip is booked as contraction and the recovery as expansion, and the monthly base includes in-year new logos, which churn more. A monthly GRR near 99% must not be compared with an annual benchmark.")
    rt.ws[f"A{trap + 9}"].font = _f(italic=True, color="52514E")
    for c, w in zip("BCDEFGHI", [10, 13, 10, 10, 10, 13, 14, 13]):
        rt.ws.column_dimensions[c].width = w

    # ---------------- Customer_ARR (data)
    ca = Sheet(wb, "Customer_ARR", "Account-Level ARR at July 2026 ($)", "Sorted by billed ARR, descending. Billed ARR = 12 x billed MRR.")
    arr = rq["customer_arr"]
    heads = ["Customer", "Segment", "Industry", "Channel", "Pricing", "Term (months)", "Discount", "Months to renewal", "Billed ARR", "List ARR"]
    ca.header(4, heads)
    for i, row in enumerate(arr.itertuples(index=False)):
        rr = 5 + i
        vals = [row.customer_id, row.segment, row.industry, row.channel, row.pricing_model, int(row.contract_term_months),
                float(row.discount_pct), int(row.months_to_renewal), round(float(row.arr), 2), round(float(row.list_arr), 2)]
        fmts = [None, None, None, None, None, NUM, PCT, NUM, USD, USD]
        for j, (v, fm) in enumerate(zip(vals, fmts)):
            c = ca.ws.cell(row=rr, column=1 + j, value=v)
            c.font = _f(BLUE if isinstance(v, (int, float)) else BLACK)
            if fm:
                c.number_format = fm
    ca_last = 4 + len(arr)
    for c, w in zip("ABCDEFGHIJ", [11, 12, 14, 11, 9, 9, 9, 10, 13, 13]):
        ca.ws.column_dimensions[c].width = w
    ca.ws.freeze_panes = "A5"
    R = f"Customer_ARR!$I$5:$I${ca_last}"

    # ---------------- Concentration
    co = Sheet(wb, "Concentration", "Customer Concentration (billed ARR, July 2026)", "All formulas read Customer_ARR; HHI on a 0 to 10,000 scale.")
    co.header(4, ["Metric", "Value"])
    conc = [("Active customers", f"=COUNT({R})", NUM), ("Total billed ARR ($)", f"=SUM({R})", USD),
            ("Largest customer share", f"=LARGE({R},1)/B6", PCT),
            ("Top 10 share", f"=SUMPRODUCT(LARGE({R},ROW($1:$10)))/B6", PCT),
            ("Top 20 share", f"=SUMPRODUCT(LARGE({R},ROW($1:$20)))/B6", PCT),
            ("Top 50 share", f"=SUMPRODUCT(LARGE({R},ROW($1:$50)))/B6", PCT),
            ("Top 10% of customers, count", "=ROUNDUP(0.1*B5,0)", NUM),
            ("Top 10% of customers, ARR share (list sorted descending)", f"=SUM(Customer_ARR!$I$5:INDEX(Customer_ARR!$I:$I,4+B11))/B6", PCT),
            ("HHI", f"=SUMPRODUCT(({R}/B6)^2)*10000", '#,##0.0'),
            ("Equivalent number of equal-sized customers (10,000 / HHI)", "=IF(B13=0,0,10000/B13)", NUM)]
    for i, (lab, f, fmt) in enumerate(conc):
        co.put(f"A{5 + i}", lab); co.put(f"B{5 + i}", f, fmt)
    co.put("A16", "A single-account share this low is a property of the simulated size distribution; in real diligence concentration is often the first red flag, so the test matters more than this result.")
    co.ws["A16"].font = _f(italic=True, color="52514E")
    co.section("A17", "ARR by segment")
    co.header(18, ["Segment", "Customers", "Billed ARR ($)", "Share"])
    for i, sgm in enumerate(["Enterprise", "Mid-Market", "SMB"]):
        rr = 19 + i
        co.put(f"A{rr}", sgm)
        co.put(f"B{rr}", f'=COUNTIFS(Customer_ARR!$B$5:$B${ca_last},A{rr})', NUM)
        co.put(f"C{rr}", f'=SUMIFS({R},Customer_ARR!$B$5:$B${ca_last},A{rr})', USD)
        co.put(f"D{rr}", f"=C{rr}/$B$6", PCT)
    co.section("A23", "Top 20 customers")
    co.header(24, ["Customer", "Segment", "Industry", "Billed ARR ($)", "Share", "Cumulative", "Months to renewal", "Discount"])
    for i in range(20):
        rr, src = 25 + i, 5 + i
        co.put(f"A{rr}", f"=Customer_ARR!A{src}", color=GREEN); co.put(f"B{rr}", f"=Customer_ARR!B{src}", color=GREEN)
        co.put(f"C{rr}", f"=Customer_ARR!C{src}", color=GREEN); co.put(f"D{rr}", f"=Customer_ARR!I{src}", USD, color=GREEN)
        co.put(f"E{rr}", f"=D{rr}/$B$6", PCT); co.put(f"F{rr}", f"=E{rr}" if i == 0 else f"=F{rr - 1}+E{rr}", PCT)
        co.put(f"G{rr}", f"=Customer_ARR!H{src}", NUM, color=GREEN); co.put(f"H{rr}", f"=Customer_ARR!G{src}", PCT, color=GREEN)
    co.section("A47", "Concentration trend (quarter-end months)")
    co.header(48, ["Month", "Customers", "Top 10 share", "Top 10% of customers share", "HHI"])
    for i, row in enumerate(rq["concentration_trend"].itertuples(index=False)):
        rr = 49 + i
        co.put(f"A{rr}", row.month); co.put(f"B{rr}", int(row.customers), NUM); co.put(f"C{rr}", round(row.top10, 5), PCT)
        co.put(f"D{rr}", round(row.top10pct_of_customers, 5), PCT); co.put(f"E{rr}", round(row.hhi, 3), '#,##0.0')
    for c, w in zip("BCDEFGH", [16, 16, 16, 12, 12, 12, 10]):
        co.ws.column_dimensions[c].width = w
    co.ws.column_dimensions["A"].width = 52

    # ---------------- Revenue_to_Cash
    rc = rq["revenue_to_cash"] / 1e6
    rv = Sheet(wb, "Revenue_to_Cash", "Revenue, Invoicing and Collections ($mm)", "Monthly billing; cash dated at invoice + one month + days late; failed invoices never collected.")
    rv.header(4, ["$mm"] + list(rc.index))
    rlabels = {5: "Recognized revenue", 6: "Invoiced", 7: "Check: invoiced minus revenue", 8: "Failed, never collected",
               9: "Collectible invoices", 10: "Cash collected", 11: "Opening receivables", 12: "Closing receivables (roll-forward)",
               13: "Closing receivables per ledger", 15: "Check: roll-forward minus ledger", 17: "Ending billed ARR",
               19: "Cash conversion (cash / revenue)", 20: "Failed collections, % of revenue", 21: "DSO (days)",
               22: "Run-rate conversion (revenue x 4 / ending ARR)"}
    for r_, lab in rlabels.items():
        rv.put(f"A{r_}", lab)
    for k, (qt, v) in enumerate(rc.iterrows()):
        c = L(2 + k)
        rv.put(f"{c}5", round(v["revenue"], 5), MM); rv.put(f"{c}6", round(v["invoiced"], 5), MM)
        rv.put(f"{c}7", f"=ROUND({c}6-{c}5,4)", MM); rv.put(f"{c}8", round(v["failed_uncollected"], 5), MM)
        rv.put(f"{c}9", f"={c}6-{c}8", MM); rv.put(f"{c}10", round(v["cash_collected"], 5), MM)
        rv.put(f"{c}11", 0 if k == 0 else f"={L(1 + k)}13", MM)
        rv.put(f"{c}12", f"={c}11+{c}9-{c}10", MM); rv.put(f"{c}13", round(v["ending_ar"], 5), MM)
        rv.put(f"{c}15", f"=ROUND({c}12-{c}13,3)", MM); rv.put(f"{c}17", round(v["ending_arr"], 5), MM)
        rv.put(f"{c}19", f"=IF({c}5=0,0,{c}10/{c}5)", PCT); rv.put(f"{c}20", f"=IF({c}5=0,0,{c}8/{c}5)", PCT)
        rv.put(f"{c}21", f"=IF({c}5=0,0,{c}13/{c}5*{B['dpq']})", '0.0'); rv.put(f"{c}22", f"=IF({c}17=0,0,{c}5*4/{c}17)", PCT)
    rv.put("A24", "The first quarter's opening receivables are zero because no invoices exist before January 2023.")
    rv.put("A25", "Every account is billed monthly, so deferred revenue is zero by construction; with annual upfront billing a deferred-revenue line would sit between ARR and cash.")
    for a in ("A24", "A25"):
        rv.ws[a].font = _f(italic=True, color="52514E")
    for k in range(len(rc) + 1):
        rv.ws.column_dimensions[L(2 + k)].width = 10
    rv.ws.column_dimensions["A"].width = 46
    rv_last = L(1 + len(rc))

    # ---------------- Renewals
    sch = rq["renewal_schedule"] / 1e6
    rates = rq["renewal_rates"]
    rn = Sheet(wb, "Renewals", "ARR by Renewal Window ($mm, billed, July 2026)", "Committed contracts by the quarter they renew; monthly contracts can leave any month.")
    segs = ["Enterprise", "Mid-Market", "SMB"]
    rn.header(4, ["Renewal window"] + segs + ["Total"])
    order = [b for b in sch.index if b[:4].isdigit()] + ["Beyond 12 months", "Monthly (any month)"]
    for i, bkt in enumerate(order):
        rr = 5 + i
        label = bkt + (" (Aug to Sep)" if bkt == "2026Q3" else " (Jul only)" if bkt == "2027Q3" else "")
        rn.put(f"A{rr}", label)
        for j, sgm in enumerate(segs):
            rn.put(f"{L(2 + j)}{rr}", round(float(sch.loc[bkt, sgm]) if bkt in sch.index else 0.0, 5), MM)
        rn.put(f"E{rr}", f"=SUM(B{rr}:D{rr})", MM)
    n_fwd = sum(1 for b in order if b[:4].isdigit())
    tot = 5 + len(order)
    rn.put(f"A{tot}", "Total billed ARR")
    for j in range(4):
        c = L(2 + j)
        rn.put(f"{c}{tot}", f"=SUM({c}5:{c}{tot - 1})", MM)
    base = tot + 2
    rn.section(f"A{base}", "Expected ARR not renewed, next 12 months")
    rn.header(base + 1, ["Line"] + segs + ["Total"])
    rn.put(f"A{base + 2}", "Committed ARR renewing in next 12 months")
    rn.put(f"A{base + 3}", "Non-renewal rate, contracts ending Aug 2025 to Jun 2026")
    rn.put(f"A{base + 4}", "Expected committed ARR not renewed")
    rn.put(f"A{base + 5}", "Monthly-contract ARR")
    rn.put(f"A{base + 6}", "12-month gross loss rate, monthly contracts (1 - GRR)")
    rn.put(f"A{base + 7}", "Expected monthly-contract ARR lost")
    rn.put(f"A{base + 8}", "Total expected ARR lost, 12 months")
    rn.put(f"A{base + 9}", "As % of total billed ARR")
    for j, sgm in enumerate(segs):
        c = L(2 + j)
        rn.put(f"{c}{base + 2}", f"=SUM({c}5:{c}{4 + n_fwd})", MM)
        rn.put(f"{c}{base + 3}", round(float(rates.loc[sgm, "non_renewal_rate"]), 5), PCT,
               note=f"{int(rates.loc[sgm, 'contracts'])} committed contracts reached term in the window (contracts table).")
        rn.put(f"{c}{base + 4}", f"={c}{base + 2}*{c}{base + 3}", MM)
        rn.put(f"{c}{base + 5}", f"={c}{tot - 1}", MM)
        rn.put(f"{c}{base + 6}", f"=1-Retention!$D${ret_monthly_row}", PCT)
        rn.put(f"{c}{base + 7}", f"={c}{base + 5}*{c}{base + 6}", MM)
        rn.put(f"{c}{base + 8}", f"={c}{base + 4}+{c}{base + 7}", MM)
        rn.put(f"{c}{base + 9}", f"=IF({c}{tot}=0,0,{c}{base + 8}/{c}{tot})", PCT)
    for rr in (base + 2, base + 4, base + 5, base + 7, base + 8):
        rn.put(f"E{rr}", f"=SUM(B{rr}:D{rr})", MM)
    rn.put(f"E{base + 9}", f"=E{base + 8}/E{tot}", PCT)
    rn.put(f"A{base + 11}", "Ignores contraction at renewal and early termination, so it understates gross loss; compare with 1 - portfolio GRR on the Retention sheet.")
    rn.ws[f"A{base + 11}"].font = _f(italic=True, color="52514E")
    for c in "BCDE":
        rn.ws.column_dimensions[c].width = 13
    rn.ws.column_dimensions["A"].width = 56
    renew_total = f"Renewals!$E${base + 2}"; lost_total = f"Renewals!$E${base + 8}"; lost_pct = f"Renewals!$E${base + 9}"

    # ---------------- Sensitivity
    se = Sheet(wb, "Sensitivity", "Forward 12-Month ARR Sensitivity ($mm, list price)", "Ending ARR = opening ARR x (GRR + expansion rate) + new logo ARR. Rows vary GRR, columns vary expansion.")
    se.header(4, ["Driver", "Value", "Source"])
    drv = [("Opening ARR (latest quarter close)", f"=ARR_Bridge!{last}10", MM, "ARR_Bridge"),
           ("Base 12m GRR (portfolio cohort)", "=Retention!D5", PCT, "Retention"),
           ("Base expansion rate (NRR - GRR)", "=Retention!E5-Retention!D5", PCT, "Retention"),
           ("New logo ARR, TTM", "=ARR_Bridge!B27", MM, "ARR_Bridge"),
           ("Gross margin", f"={B['gm']}", PCT, "Inputs"),
           ("Base-case ending ARR", "=B5*(B6+B7)+B8", MM, "Formula"),
           ("Base-case ARR growth", "=B10/B5-1", PCT, "Formula"),
           ("Value of 1pt of GRR: ARR ($mm)", "=B5*0.01", MM, "Formula"),
           ("Value of 1pt of GRR: annual gross profit ($mm)", "=B12*B9", MM, "Formula")]
    for i, (lab, f, fmt, src) in enumerate(drv):
        se.put(f"A{5 + i}", lab); se.put(f"B{5 + i}", f, fmt); se.put(f"C{5 + i}", src)
    se.section("A16", "Ending ARR ($mm): GRR (rows) x expansion rate (columns)")
    steps = [-0.04, -0.02, 0.0, 0.02, 0.04]
    grr_rows = [0.84, 0.86, 0.88, 0.90, 0.92, 0.94]
    se.put("A17", "GRR \\ expansion", fill=HEAD)
    for j, d in enumerate(steps):
        se.put(f"{L(2 + j)}17", f"=$B$7+({d})", PCT, fill=HEAD)
    for i, g in enumerate(grr_rows):
        rr = 18 + i
        se.put(f"A{rr}", g, PCT, fill=KEY if i == 0 else None)
        for j in range(len(steps)):
            c = L(2 + j)
            se.put(f"{c}{rr}", f"=$B$5*($A{rr}+{c}$17)+$B$8", MM)
    se.put("A25", "GRR rows are inputs (blue); column headers step the base expansion rate by 2pp. 84% and 91% bracket the Benchmarkit and SaaS Capital medians.")
    se.ws["A25"].font = _f(italic=True, color="52514E")
    se.section("A27", "ARR growth vs base case")
    se.put("A28", "GRR \\ expansion", fill=HEAD)
    for j in range(len(steps)):
        se.put(f"{L(2 + j)}28", f"={L(2 + j)}17", PCT, fill=HEAD)
    for i in range(len(grr_rows)):
        rr = 29 + i
        se.put(f"A{rr}", f"=A{18 + i}", PCT)
        for j in range(len(steps)):
            c = L(2 + j)
            se.put(f"{c}{rr}", f"={c}{18 + i}/$B$5-1", PCT)
    for c in "BCDEF":
        se.ws.column_dimensions[c].width = 12
    se.ws.column_dimensions["A"].width = 48

    # ---------------- Diligence
    dg = Sheet(wb, "Diligence", "Diligence Benchmark at Close", "Our Dec 2023 to Dec 2024 cohort vs SaaS Capital 2025 medians (same window). Calibration window: agreement is by design.")
    dg.header(4, ["Cut", "Accounts", "Our GRR", "Benchmark GRR", "GRR gap", "Our NRR", "Benchmark NRR", "NRR gap", "Note"])
    for i, row in enumerate(dil["benchmark_table"].itertuples(index=False)):
        rr = 5 + i
        dg.put(f"A{rr}", row.cut); dg.put(f"B{rr}", int(row.ours_accounts), NUM)
        dg.put(f"C{rr}", round(float(row.ours_grr), 5), PCT); dg.put(f"D{rr}", float(row.bench_grr), PCT); dg.put(f"E{rr}", f"=C{rr}-D{rr}", PCT)
        dg.put(f"F{rr}", round(float(row.ours_nrr), 5), PCT); dg.put(f"G{rr}", float(row.bench_nrr), PCT); dg.put(f"H{rr}", f"=F{rr}-G{rr}", PCT)
        dg.put(f"I{rr}", "Fewer than 30 accounts; not compared" if row.small_sample else ("Whole portfolio vs this benchmark group" if row.match == "portfolio" else ""))
    for c, w in zip("BCDEFGHI", [10, 10, 13, 10, 10, 13, 10, 40]):
        dg.ws.column_dimensions[c].width = w
    dg.ws.column_dimensions["A"].width = 34

    # ---------------- Plan_vs_Actual
    uw = dil["underwrite"]
    pv = Sheet(wb, "Plan_vs_Actual", "Underwriting Forecast vs Actual (list ARR, $mm)", "Forecast and band set at close from pre-close months only; actuals after close.")
    pv.header(4, ["Month", "Base case", "Band low (p05)", "Band high (p95)", "Actual", "Base vs actual", "Inside 90% band"])
    for i, (mth, row) in enumerate(uw.iterrows()):
        rr = 5 + i
        pv.put(f"A{rr}", pd.Timestamp(mth).strftime("%Y-%m"))
        for col, key in zip("BCDE", ["base", "p05", "p95", "actual"]):
            pv.put(f"{col}{rr}", round(float(row[key]) * 12 / 1e6, 4), MM)
        pv.put(f"F{rr}", f"=IF(E{rr}=0,0,B{rr}/E{rr}-1)", PCT)
        pv.put(f"G{rr}", f'=IF(AND(E{rr}>=C{rr},E{rr}<=D{rr}),1,0)', '0')
    last_pv = 4 + len(uw)
    pv.put(f"A{last_pv + 2}", "Months inside the 90% band"); pv.put(f"B{last_pv + 2}", f"=AVERAGE(G5:G{last_pv})", PCT)
    pv.put(f"A{last_pv + 3}", "Forecast error at the last month"); pv.put(f"B{last_pv + 3}", f"=F{last_pv}", PCT)
    rp = dil["retention_plan"]
    pv.section(f"A{last_pv + 5}", "Retention plan (diligence GRR/NRR held flat) vs actual rolling 12-month cohorts")
    pv.header(last_pv + 6, ["Period end", "Plan GRR", "Actual GRR", "GRR variance", "Plan NRR", "Actual NRR", "NRR variance"])
    for i, row in enumerate(rp.itertuples(index=False)):
        rr = last_pv + 7 + i
        pv.put(f"A{rr}", str(row.period_end)[:7]); pv.put(f"B{rr}", round(float(row.plan_grr), 5), PCT); pv.put(f"C{rr}", round(float(row.actual_grr), 5), PCT)
        pv.put(f"D{rr}", f"=C{rr}-B{rr}", PCT); pv.put(f"E{rr}", round(float(row.plan_nrr), 5), PCT); pv.put(f"F{rr}", round(float(row.actual_nrr), 5), PCT); pv.put(f"G{rr}", f"=F{rr}-E{rr}", PCT)
    for c in "BCDEFG":
        pv.ws.column_dimensions[c].width = 13
    pv.ws.column_dimensions["A"].width = 44

    # ---------------- Summary (placed second)
    sm = Sheet(wb, "Summary", "Quality of Revenue Summary", "Every value links to a working sheet.")
    sm.header(4, ["KPI", "Value", "Reference point", "Read"])
    kp = [("Diligence GRR, Dec 2023 to Dec 2024", "=Diligence!C5", PCT, "=Diligence!D5", "vs SaaS Capital 2025 median, same window (calibrated)"),
          ("Diligence NRR, Dec 2023 to Dec 2024", "=Diligence!F5", PCT, "=Diligence!G5", "vs SaaS Capital 2025 median, same window (calibrated)"),
          ("Underwriting forecast error, last month", f"=Plan_vs_Actual!B{last_pv + 3}", PCT, None, "Base case vs actual list ARR"),
          ("Months inside the 90% band set at close", f"=Plan_vs_Actual!B{last_pv + 2}", PCT, None, "Out-of-sample interval check"),
          ("Closing list ARR, latest quarter ($mm)", f"=ARR_Bridge!{last}10", MM, None, "Scale"),
          ("ARR growth, TTM", "=ARR_Bridge!B31", PCT, f"={B['sc_growth']}", "vs SaaS Capital median revenue growth (different measure, context only)"),
          ("12m cohort GRR, now", "=Retention!D5", PCT, f"={B['sc_grr']}", "vs SaaS Capital 2025 median; Benchmarkit 2026 median is 84%"),
          ("12m cohort NRR, now", "=Retention!E5", PCT, f"={B['sc_nrr']}", "vs SaaS Capital 2025 median"),
          ("Expansion share of gross new ARR, TTM", "=ARR_Bridge!B32", PCT, f"={B['bm_exp']}", "vs Benchmarkit median"),
          ("Top 10 customers, share of ARR", "=Concentration!B8", PCT, None, "Concentration"),
          ("HHI", "=Concentration!B13", '#,##0.0', None, "10,000 / HHI = number of equal-sized customers with the same concentration"),
          ("Cash conversion, latest quarter", f"=Revenue_to_Cash!{rv_last}19", PCT, None, "Cash collected / revenue"),
          ("DSO, latest quarter (days)", f"=Revenue_to_Cash!{rv_last}21", '0.0', None, "Driven by the one-month terms assumption"),
          ("Failed collections, % of revenue, latest quarter", f"=Revenue_to_Cash!{rv_last}20", PCT, None, "Leakage between billing and cash"),
          ("Committed ARR renewing in next 12 months ($mm)", f"={renew_total}", MM, None, "Renewal exposure"),
          ("Expected ARR lost in next 12 months ($mm)", f"={lost_total}", MM, None, "Historical non-renewal rates applied"),
          ("Expected ARR lost, % of ARR", f"={lost_pct}", PCT, None, "Compare with 1 - GRR"),
          ("Value of 1pt of GRR, annual gross profit ($mm)", "=Sensitivity!B13", MM, None, "Uses the gross margin input")]
    for i, (lab, f, fmt, ref, read) in enumerate(kp):
        rr = 5 + i
        sm.put(f"A{rr}", lab); sm.put(f"B{rr}", f, fmt, color=GREEN)
        if ref:
            sm.put(f"C{rr}", ref, fmt, color=GREEN)
        sm.put(f"D{rr}", read)
    for c, w in zip("BCD", [12, 14, 60]):
        sm.ws.column_dimensions[c].width = w
    sm.ws.column_dimensions["A"].width = 50

    order = ["Cover", "Summary", "Inputs", "Diligence", "Plan_vs_Actual", "ARR_Bridge", "Retention", "Concentration", "Revenue_to_Cash", "Renewals",
             "Sensitivity", "Customer_ARR", "Monthly_Bridge"]
    wb._sheets = [wb[n] for n in order]
    wb.active = 1
    for ws in wb.worksheets:
        ws.sheet_properties.tabColor = "2A78D6" if ws.title in ("Summary", "Cover") else None
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path
